- name: Deploy Docker
  hosts: all 
  remote_user: aecid
  become: true
  roles:
#    - role: aeciduser
#      vars:
#            # pass: aecid
#            aeciduser_pass: "$6$9AqxTPJqYsFXwgPN$xAC4y1Vndk00EaBCuFcJC37BYDYYVAgt9SHymg15KSdKddZnwG.SsQaJvHarH4DYQj3tuboeLa4G5EfL7itcC0"
#    - role: aecidtools
#      vars:
#            aecidtools_user: "aecid"
#    - role: manage_unattended_upgrades
#    - role: auditd
    - role: atb-ansible-dockerce
    - role: /home/mlanger/ait/dockerszenario/atb-ansible-nextcloudrce
      vars:
        nextcloud_rce_domain: "localhost:8080"
        nextcloud_rce_docker_compose_template: "docker-compose-mail.yml.j2"
    - role: /home/mlanger/ait/dockerszenario/atb-ansible-vulndockerd
      vars:
        vulndockerd_socket: "tcp://0.0.0.0:2375"
  tasks:
    - name: Copy mail build context files
      ansible.builtin.copy:
        src: "/home/mlanger/ait/dockerszenario/attackbed/ansible/deploy/docker/mail/{{ item }}"
        dest: "{{ nextcloud_rce_dir }}/mail/{{ item }}"
        mode: '0644'
      loop:
        - Dockerfile
        - supervisord.conf

    - name: Ensure mailconfig directories exist
      ansible.builtin.file:
        path: "{{ nextcloud_rce_dir }}/mailconfig/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - postfix
        - dovecot
        - dovecot/conf.d

    - name: Deploy Dovecot/Postfix config files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ nextcloud_rce_dir }}/mailconfig/{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: 'dovecot-10-auth.conf.j2', dest: 'dovecot/conf.d/10-auth.conf' }
        - { src: 'dovecot-10-mail.conf.j2', dest: 'dovecot/conf.d/10-mail.conf' }
        - { src: 'dovecot-sql.conf.ext.j2', dest: 'dovecot/dovecot-sql.conf.ext' }
        - { src: 'dovecot-10-master.conf.j2', dest: 'dovecot/conf.d/10-master.conf' }
        - { src: 'postfix-main.cf.j2', dest: 'postfix/main.cf' }
        - { src: 'postfix-master.cf.j2', dest: 'postfix/master.cf' }
        - { src: 'postfix-mysql_virtual_mailbox_maps.cf.j2', dest: 'postfix/mysql_virtual_mailbox_maps.cf' }

    - name: Start containers
      ansible.builtin.shell: "docker compose up -d"
      args:
        chdir: "{{ nextcloud_rce_dir }}"